{"level":"error","message":"Unable to connect to database: getaddrinfo EAI_AGAIN postgres","name":"SequelizeConnectionError","original":{"code":"EAI_AGAIN","errno":-3001,"hostname":"postgres","syscall":"getaddrinfo"},"parent":{"code":"EAI_AGAIN","errno":-3001,"hostname":"postgres","syscall":"getaddrinfo"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: getaddrinfo EAI_AGAIN postgres\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-09-02 14:12:23"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:00"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:02"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:04"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:06"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:08"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:13"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:20"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:31"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:48"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:14:22"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:15:17"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:16:20"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:17:21"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:18:24"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:51:28"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:52:33"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"myuser\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"myuser\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:36"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"myuser\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"myuser\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:40"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"myuser\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"myuser\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:43"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"myuser\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"myuser\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:45"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"AmolYadav\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":105,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":105,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"AmolYadav\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:47"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:49"}
{"level":"error","message":"Unable to connect to database: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","name":"SequelizeConnectionError","original":{},"parent":{},"service":"ai-platform-backend","stack":"SequelizeConnectionError: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:507:28)\n    at Client._handleAuthSASLContinue (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:284:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-02 19:53:51"}
{"level":"info","message":"Database connection established successfully","service":"ai-platform-backend","timestamp":"2025-09-02 19:53:52"}
{"level":"info","message":"Database connection established successfully","service":"ai-platform-backend","timestamp":"2025-09-02 19:53:58"}
{"level":"info","message":"Database connection established successfully","service":"ai-platform-backend","timestamp":"2025-09-02 19:56:04"}
{"level":"info","message":"Database connection established successfully","service":"ai-platform-backend","timestamp":"2025-09-02 19:56:08"}
{"level":"info","message":"Database connection established successfully","service":"ai-platform-backend","timestamp":"2025-09-02 19:56:53"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:57:28"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:58:01"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:58:10"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:58:21"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:58:38"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:58:43"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:58:52"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:59:01"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:59:08"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:59:21"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:59:27"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:59:29"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 19:59:36"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 20:00:10"}
{"level":"info","message":"All models initialized successfully","service":"backend","timestamp":"2025-09-02 20:00:10"}
{"level":"error","message":"Unable to connect to database: default for column \"status\" cannot be cast automatically to type enum_users_status","name":"SequelizeDatabaseError","original":{"code":"42804","file":"tablecmds.c","length":153,"line":"13246","name":"error","routine":"ATExecAlterColumnType","severity":"ERROR","sql":"ALTER TABLE \"users\" ALTER COLUMN \"status\" DROP NOT NULL;ALTER TABLE \"users\" ALTER COLUMN \"status\" SET DEFAULT 'active';DO 'BEGIN CREATE TYPE \"public\".\"enum_users_status\" AS ENUM(''active'', ''inactive'', ''banned''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"users\" ALTER COLUMN \"status\" TYPE \"public\".\"enum_users_status\" USING (\"status\"::\"public\".\"enum_users_status\");"},"parameters":{},"parent":{"code":"42804","file":"tablecmds.c","length":153,"line":"13246","name":"error","routine":"ATExecAlterColumnType","severity":"ERROR","sql":"ALTER TABLE \"users\" ALTER COLUMN \"status\" DROP NOT NULL;ALTER TABLE \"users\" ALTER COLUMN \"status\" SET DEFAULT 'active';DO 'BEGIN CREATE TYPE \"public\".\"enum_users_status\" AS ENUM(''active'', ''inactive'', ''banned''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"users\" ALTER COLUMN \"status\" TYPE \"public\".\"enum_users_status\" USING (\"status\"::\"public\".\"enum_users_status\");"},"service":"backend","sql":"ALTER TABLE \"users\" ALTER COLUMN \"status\" DROP NOT NULL;ALTER TABLE \"users\" ALTER COLUMN \"status\" SET DEFAULT 'active';DO 'BEGIN CREATE TYPE \"public\".\"enum_users_status\" AS ENUM(''active'', ''inactive'', ''banned''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"users\" ALTER COLUMN \"status\" TYPE \"public\".\"enum_users_status\" USING (\"status\"::\"public\".\"enum_users_status\");","stack":"Error\n    at Query.run (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:50:25)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async User.sync (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:984:11)\n    at async Sequelize._syncModelsWithCyclicReferences (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\sequelize.js:395:7)\n    at async initializeDatabase (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\database.js:38:5)\n    at async initialize (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\app.js:35:5)","timestamp":"2025-09-02 20:00:10"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 20:02:09"}
{"level":"info","message":"All models initialized successfully","service":"backend","timestamp":"2025-09-02 20:02:09"}
{"level":"error","message":"Unable to connect to database: default for column \"visibility\" cannot be cast automatically to type enum_projects_visibility","name":"SequelizeDatabaseError","original":{"code":"42804","file":"tablecmds.c","length":164,"line":"13246","name":"error","routine":"ATExecAlterColumnType","severity":"ERROR","sql":"ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" DROP NOT NULL;ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" SET DEFAULT 'private';DO 'BEGIN CREATE TYPE \"public\".\"enum_projects_visibility\" AS ENUM(''private'', ''public'', ''shared''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" TYPE \"public\".\"enum_projects_visibility\" USING (\"visibility\"::\"public\".\"enum_projects_visibility\");"},"parameters":{},"parent":{"code":"42804","file":"tablecmds.c","length":164,"line":"13246","name":"error","routine":"ATExecAlterColumnType","severity":"ERROR","sql":"ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" DROP NOT NULL;ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" SET DEFAULT 'private';DO 'BEGIN CREATE TYPE \"public\".\"enum_projects_visibility\" AS ENUM(''private'', ''public'', ''shared''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" TYPE \"public\".\"enum_projects_visibility\" USING (\"visibility\"::\"public\".\"enum_projects_visibility\");"},"service":"backend","sql":"ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" DROP NOT NULL;ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" SET DEFAULT 'private';DO 'BEGIN CREATE TYPE \"public\".\"enum_projects_visibility\" AS ENUM(''private'', ''public'', ''shared''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" TYPE \"public\".\"enum_projects_visibility\" USING (\"visibility\"::\"public\".\"enum_projects_visibility\");","stack":"Error\n    at Query.run (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:50:25)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Project.sync (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:984:11)\n    at async Sequelize._syncModelsWithCyclicReferences (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\sequelize.js:395:7)\n    at async initializeDatabase (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\database.js:38:5)\n    at async initialize (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\app.js:35:5)","timestamp":"2025-09-02 20:02:10"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 20:03:27"}
{"level":"info","message":"All models initialized successfully","service":"backend","timestamp":"2025-09-02 20:03:27"}
{"level":"info","message":"Database synchronized","service":"backend","timestamp":"2025-09-02 20:03:28"}
{"level":"info","message":"Database connection established successfully","service":"backend","timestamp":"2025-09-02 20:03:45"}
{"level":"info","message":"All models initialized successfully","service":"backend","timestamp":"2025-09-02 20:03:45"}
{"level":"info","message":"Database synchronized","service":"backend","timestamp":"2025-09-02 20:03:46"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 20:29:15"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 20:50:16"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 20:50:23"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 20:54:25"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:00:45"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:00:46"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:24"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:27"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:34"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:42"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:45"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:51"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:53"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:55"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:57"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:01"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:05"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:13"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:15"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:18"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:24"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:31"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:38"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:47"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:56"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:58"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:07:42"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:07:51"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:11:46"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:12:07"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:12:25"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:12:42"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:13:09"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:19:11"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:19:19"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:19:25"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:24:32"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:24:39"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:26:58"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:57:28"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:01:29"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:09:00"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:11:21"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:11:27"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:11:32"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:11:34"}
