{"level":"error","message":"Unable to connect to database: getaddrinfo EAI_AGAIN postgres","name":"SequelizeConnectionError","original":{"code":"EAI_AGAIN","errno":-3001,"hostname":"postgres","syscall":"getaddrinfo"},"parent":{"code":"EAI_AGAIN","errno":-3001,"hostname":"postgres","syscall":"getaddrinfo"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: getaddrinfo EAI_AGAIN postgres\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-09-02 14:12:23"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:00"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:02"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:04"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:06"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:08"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:13"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:20"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:31"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:13:48"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:14:22"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:15:17"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:16:20"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:17:21"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"334","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:517:28)\n    at /app/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","timestamp":"2025-09-02 14:18:24"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:51:28"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:52:33"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"myuser\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"myuser\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:36"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"myuser\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"myuser\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:40"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"myuser\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"myuser\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:43"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"myuser\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"myuser\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:45"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"AmolYadav\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":105,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":105,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"AmolYadav\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:47"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"ai-platform-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 19:53:49"}
{"level":"error","message":"Unable to connect to database: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","name":"SequelizeConnectionError","original":{},"parent":{},"service":"ai-platform-backend","stack":"SequelizeConnectionError: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:507:28)\n    at Client._handleAuthSASLContinue (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:284:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-02 19:53:51"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"ai-platform-backend","stack":"Error: No Sequelize instance passed\n    at Project.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Project.js:6:9)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:53:52"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"ai-platform-backend","stack":"Error: No Sequelize instance passed\n    at Project.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Project.js:6:9)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:53:58"}
{"level":"error","message":"Unable to connect to database: Unexpected end of input","service":"ai-platform-backend","stack":"C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Project.js:80\nclass proj\n          \n\nSyntaxError: Unexpected end of input\n    at wrapSafe (node:internal/modules/cjs/loader:1669:18)\n    at Module._compile (node:internal/modules/cjs/loader:1712:20)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)\n    at initializeModels (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\database.js:51:3)","timestamp":"2025-09-02 19:56:04"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"ai-platform-backend","stack":"Error: No Sequelize instance passed\n    at Project.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Project.js:6:9)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:56:08"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"ai-platform-backend","stack":"Error: No Sequelize instance passed\n    at Dataset.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Dataset.js:6:9)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:56:53"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at Dataset.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Dataset.js:6:9)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:57:28"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at Dataset.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Dataset.js:6:9)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:58:01"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at Dataset.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Dataset.js:6:9)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:58:10"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at ModelRecord.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\Model.js:6:13)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:58:21"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at TrainingJob.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\TrainingJob.js:6:13)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:58:38"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at TrainingJob.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\TrainingJob.js:6:13)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:58:43"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at TrainingJob.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\TrainingJob.js:6:13)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:58:52"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at VastInstance.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\VastInstance.js:6:14)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:59:01"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at VastInstance.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\VastInstance.js:6:14)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:59:08"}
{"level":"error","message":"Unable to connect to database: Identifier 'getSequelize' has already been declared","service":"backend","stack":"C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\User.js:98\nconst { getSequelize } = require('../config/database');\n        ^\n\nSyntaxError: Identifier 'getSequelize' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1669:18)\n    at Module._compile (node:internal/modules/cjs/loader:1712:20)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)\n    at initializeModels (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\database.js:50:3)","timestamp":"2025-09-02 19:59:21"}
{"level":"error","message":"Unable to connect to database: No Sequelize instance passed","service":"backend","stack":"Error: No Sequelize instance passed\n    at VastInstance.init (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:662:13)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\VastInstance.js:6:14)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)","timestamp":"2025-09-02 19:59:27"}
{"level":"error","message":"Unable to connect to database: Identifier 'getSequelize' has already been declared","service":"backend","stack":"C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\User.js:98\nconst { getSequelize } = require('../config/database');\n        ^\n\nSyntaxError: Identifier 'getSequelize' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1669:18)\n    at Module._compile (node:internal/modules/cjs/loader:1712:20)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)\n    at initializeModels (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\database.js:50:3)","timestamp":"2025-09-02 19:59:29"}
{"level":"error","message":"Unable to connect to database: Identifier 'getSequelize' has already been declared","service":"backend","stack":"C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\models\\User.js:98\nconst { getSequelize } = require('../config/database');\n        ^\n\nSyntaxError: Identifier 'getSequelize' has already been declared\n    at wrapSafe (node:internal/modules/cjs/loader:1669:18)\n    at Module._compile (node:internal/modules/cjs/loader:1712:20)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)\n    at initializeModels (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\database.js:50:3)","timestamp":"2025-09-02 19:59:36"}
{"level":"error","message":"Unable to connect to database: default for column \"status\" cannot be cast automatically to type enum_users_status","name":"SequelizeDatabaseError","original":{"code":"42804","file":"tablecmds.c","length":153,"line":"13246","name":"error","routine":"ATExecAlterColumnType","severity":"ERROR","sql":"ALTER TABLE \"users\" ALTER COLUMN \"status\" DROP NOT NULL;ALTER TABLE \"users\" ALTER COLUMN \"status\" SET DEFAULT 'active';DO 'BEGIN CREATE TYPE \"public\".\"enum_users_status\" AS ENUM(''active'', ''inactive'', ''banned''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"users\" ALTER COLUMN \"status\" TYPE \"public\".\"enum_users_status\" USING (\"status\"::\"public\".\"enum_users_status\");"},"parameters":{},"parent":{"code":"42804","file":"tablecmds.c","length":153,"line":"13246","name":"error","routine":"ATExecAlterColumnType","severity":"ERROR","sql":"ALTER TABLE \"users\" ALTER COLUMN \"status\" DROP NOT NULL;ALTER TABLE \"users\" ALTER COLUMN \"status\" SET DEFAULT 'active';DO 'BEGIN CREATE TYPE \"public\".\"enum_users_status\" AS ENUM(''active'', ''inactive'', ''banned''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"users\" ALTER COLUMN \"status\" TYPE \"public\".\"enum_users_status\" USING (\"status\"::\"public\".\"enum_users_status\");"},"service":"backend","sql":"ALTER TABLE \"users\" ALTER COLUMN \"status\" DROP NOT NULL;ALTER TABLE \"users\" ALTER COLUMN \"status\" SET DEFAULT 'active';DO 'BEGIN CREATE TYPE \"public\".\"enum_users_status\" AS ENUM(''active'', ''inactive'', ''banned''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"users\" ALTER COLUMN \"status\" TYPE \"public\".\"enum_users_status\" USING (\"status\"::\"public\".\"enum_users_status\");","stack":"Error\n    at Query.run (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:50:25)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async User.sync (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:984:11)\n    at async Sequelize._syncModelsWithCyclicReferences (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\sequelize.js:395:7)\n    at async initializeDatabase (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\database.js:38:5)\n    at async initialize (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\app.js:35:5)","timestamp":"2025-09-02 20:00:10"}
{"level":"error","message":"Unable to connect to database: default for column \"visibility\" cannot be cast automatically to type enum_projects_visibility","name":"SequelizeDatabaseError","original":{"code":"42804","file":"tablecmds.c","length":164,"line":"13246","name":"error","routine":"ATExecAlterColumnType","severity":"ERROR","sql":"ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" DROP NOT NULL;ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" SET DEFAULT 'private';DO 'BEGIN CREATE TYPE \"public\".\"enum_projects_visibility\" AS ENUM(''private'', ''public'', ''shared''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" TYPE \"public\".\"enum_projects_visibility\" USING (\"visibility\"::\"public\".\"enum_projects_visibility\");"},"parameters":{},"parent":{"code":"42804","file":"tablecmds.c","length":164,"line":"13246","name":"error","routine":"ATExecAlterColumnType","severity":"ERROR","sql":"ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" DROP NOT NULL;ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" SET DEFAULT 'private';DO 'BEGIN CREATE TYPE \"public\".\"enum_projects_visibility\" AS ENUM(''private'', ''public'', ''shared''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" TYPE \"public\".\"enum_projects_visibility\" USING (\"visibility\"::\"public\".\"enum_projects_visibility\");"},"service":"backend","sql":"ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" DROP NOT NULL;ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" SET DEFAULT 'private';DO 'BEGIN CREATE TYPE \"public\".\"enum_projects_visibility\" AS ENUM(''private'', ''public'', ''shared''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"projects\" ALTER COLUMN \"visibility\" TYPE \"public\".\"enum_projects_visibility\" USING (\"visibility\"::\"public\".\"enum_projects_visibility\");","stack":"Error\n    at Query.run (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:50:25)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Project.sync (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\model.js:984:11)\n    at async Sequelize._syncModelsWithCyclicReferences (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\sequelize.js:395:7)\n    at async initializeDatabase (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\database.js:38:5)\n    at async initialize (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\app.js:35:5)","timestamp":"2025-09-02 20:02:10"}
{"code":"MODULE_NOT_FOUND","level":"error","message":"Failed to initialize application: Cannot find module '../middleware/rateLimit.middleware'\nRequire stack:\n- C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\routes\\auth.routes.js\n- C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\app.js","requireStack":["C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\routes\\auth.routes.js","C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\app.js"],"service":"backend","stack":"Error: Cannot find module '../middleware/rateLimit.middleware'\nRequire stack:\n- C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\routes\\auth.routes.js\n- C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\app.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1410:15)\n    at defaultResolveImpl (node:internal/modules/cjs/loader:1051:19)\n    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1056:22)\n    at Module._load (node:internal/modules/cjs/loader:1219:37)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)\n    at require (node:internal/modules/helpers:152:16)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\routes\\auth.routes.js:5:24)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)","timestamp":"2025-09-02 20:03:28"}
{"level":"error","message":"Failed to initialize application: Redis client not initialized","service":"backend","stack":"Error: Redis client not initialized\n    at getRedisClient (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\config\\redis.js:43:11)\n    at createRateLimit (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\middleware\\rateLimit.middleware.js:58:27)\n    at Object.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\src\\middleware\\rateLimit.middleware.js:67:12)\n    at Module._compile (node:internal/modules/cjs/loader:1738:14)\n    at Object..js (node:internal/modules/cjs/loader:1871:10)\n    at Module.load (node:internal/modules/cjs/loader:1470:32)\n    at Module._load (node:internal/modules/cjs/loader:1290:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)\n    at Module.require (node:internal/modules/cjs/loader:1493:12)","timestamp":"2025-09-02 20:03:46"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 20:29:15"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 20:50:16"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 20:50:23"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 20:54:25"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:00:45"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:00:46"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:24"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:27"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:34"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:42"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:45"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:51"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:53"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:55"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:02:57"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:01"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:05"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:13"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:15"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:18"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:24"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:31"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:38"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:47"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:56"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:03:58"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:07:42"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:07:51"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:11:46"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:12:07"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:12:25"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:12:42"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:13:09"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:19:11"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:19:19"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:19:25"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:24:32"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:24:39"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:26:58"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 21:57:28"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:01:29"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:09:00"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:11:21"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:11:27"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:11:32"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:11:34"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:15:20"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:19:38"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:19:41"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:19:48"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:19:58"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:20:22"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:20:53"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:21:03"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:21:05"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:21:07"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:21:14"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-02 22:21:21"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-04 11:39:59"}
{"level":"error","message":"Unable to connect to database: password authentication failed for user \"postgres_se\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":107,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres_se\"\n    at Client._connectionCallback (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:507:28)\n    at C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\amoly\\Desktop\\smart-evolve\\backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:507:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-09-04 11:40:23"}
